services:
  postgresdb:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - demo_data:/var/lib/postgresql/data
    networks:
      - crm-network

volumes:
  demo_data:
    name: demo_data

networks:
  crm-network:
    driver: bridge

